In [110]:
import pickle

In [111]:
from google.colab import drive
drive.mount('/content/drive' , force_remount = True)

Mounted at /content/drive

# After Temporal Correction  Model


---

These are data such that ADI are predicted from Temporal Correction  model  and variables like BF,ASSET,FC,LIT,MSW are predicted from model before Temporal Correction that is using Arch-2

In [112]:
df_2001 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/pred_final_2001.pkl','rb'))

In [113]:
df_2001

        village_code  ADI  BF  FC  ASSET  LIT  MSW
0              27378    6   1   1      2    2    1
1              27379    7   1   1      2    2    1
2              27380    7   1   1      2    2    1
3              27381    6   1   1      2    2    1
4              27382    6   1   1      2    2    1
...              ...  ...  ..  ..    ...  ...  ...
291073        644661    9   1   1      3    2    3
291074        644682    8   1   1      2    2    3
291075        644683   10   1   1      3    2    3
291076        644687   10   1   1      3    2    3
291077        644693   10   1   1      3    2    3

[291078 rows x 7 columns]

In [114]:
df_2011 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/pred_final_2011.pkl','rb'))

In [115]:
df_2011

        village_code  ADI  BF  FC  ASSET  LIT  MSW
0              27378   11   1   1      3    3    3
1              27379   13   1   3      3    3    3
2              27380   11   1   1      3    3    3
3              27381   11   1   1      3    3    3
4              27382   11   1   1      3    3    3
...              ...  ...  ..  ..    ...  ...  ...
332894        644661   13   1   3      3    3    3
332895        644682   13   1   3      3    3    3
332896        644683   13   1   3      3    3    3
332897        644687   13   1   3      3    3    3
332898        644693   13   1   3      3    3    3

[332899 rows x 7 columns]

In [116]:
df_2019 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/pred_final_2019.pkl','rb'))

In [117]:
df_2019

        village_code  ADI  BF  FC  ASSET  LIT  MSW
0              27378   12   1   3      3    3    3
1              27379   12   1   3      3    3    3
2              27380   12   1   3      3    3    3
3              27381   10   1   1      3    3    3
4              27382   12   1   3      3    3    3
...              ...  ...  ..  ..    ...  ...  ...
309514        644661   13   3   3      3    2    3
309515        644682   12   1   3      3    2    3
309516        644683   14   3   3      3    2    3
309517        644687   12   1   3      3    2    3
309518        644693    9   1   1      3    2    3

[309519 rows x 7 columns]

# Before Temporal Correction Model

In [118]:
df_2001 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/ADI_Predictions/pred_2001.pkl','rb'))

In [132]:
df_2001['village_code'] = df_2001.index

In [133]:
df_2001

        BF  FC  MSW  ASSET  LIT  ADI  village_code
27378    1   1    1      2    2    7         27378
27379    1   1    1      2    2    7         27379
27380    1   1    1      2    2    7         27380
27381    1   1    1      2    2    7         27381
27382    1   1    1      2    2    7         27382
...     ..  ..  ...    ...  ...  ...           ...
644661   1   1    3      3    2   10        644661
644682   1   1    3      2    2    9        644682
644683   1   1    3      3    2   10        644683
644687   1   1    3      3    2   10        644687
644693   1   1    3      3    2   10        644693

[311831 rows x 7 columns]

In [120]:
df_2011 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/ADI_Predictions/pred_2011.pkl','rb'))

In [134]:
df_2011['village_code'] = df_2011.index

In [135]:
df_2011

        BF  FC  MSW  ASSET  LIT  ADI  village_code
27378    1   1    3      3    3   11         27378
27379    1   3    3      3    3   13         27379
27380    1   1    3      3    3   11         27380
27381    1   1    3      3    3   11         27381
27382    1   1    3      3    3   11         27382
...     ..  ..  ...    ...  ...  ...           ...
644661   1   3    3      3    3   13        644661
644682   1   3    3      3    3   13        644682
644683   1   3    3      3    3   13        644683
644687   1   3    3      3    3   13        644687
644693   1   3    3      3    3   13        644693

[340953 rows x 7 columns]

In [122]:
df_2019 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/ADI_Predictions/pred_2019.pkl','rb'))

In [136]:
df_2019['village_code'] = df_2019.index

In [137]:
df_2019

        BF  FC  MSW  ASSET  LIT  ADI  village_code
27378    1   3    3      3    3   13         27378
27379    1   3    3      3    3   13         27379
27380    1   3    3      3    3   13         27380
27381    1   1    3      3    3   11         27381
27382    1   3    3      3    3   13         27382
...     ..  ..  ...    ...  ...  ...           ...
644661   3   3    3      3    2   14        644661
644682   1   3    3      3    2   12        644682
644683   3   3    3      3    2   14        644683
644687   1   3    3      3    2   12        644687
644693   1   1    3      3    2   10        644693

[309525 rows x 7 columns]

# Ground Truth Data 2011

---

This is the 2011 data that was formed after using clusters to give levels to indicators and it consists of outliered villages also,however the cluster were trained on non-outlier data

In [124]:
df_ground_truth_2011 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/ground_truth_2011.pkl','rb'))

In [125]:
df_ground_truth_2011

        village_code  ADI  BF  FC  ASSET  LIT  MSW
0              34223   11   3   1      3    2    2
1              34224   14   3   3      3    3    2
2              34225   13   2   3      3    2    3
3              34228   12   1   3      3    2    3
4              34230   12   3   2      3    2    2
...              ...  ...  ..  ..    ...  ...  ...
340948        644433   13   1   3      3    3    3
340949        644434   15   3   3      3    3    3
340950        644447   15   3   3      3    3    3
340951        644448   15   3   3      3    3    3
340952        644449   13   1   3      3    3    3

[340953 rows x 7 columns]

## Combine timeseries_pred_2001,ground_truth2011,timeseries_pred_2019

In [138]:
df_combined = df_2001.copy()

In [139]:
df_combined

        BF  FC  MSW  ASSET  LIT  ADI  village_code
27378    1   1    1      2    2    7         27378
27379    1   1    1      2    2    7         27379
27380    1   1    1      2    2    7         27380
27381    1   1    1      2    2    7         27381
27382    1   1    1      2    2    7         27382
...     ..  ..  ...    ...  ...  ...           ...
644661   1   1    3      3    2   10        644661
644682   1   1    3      2    2    9        644682
644683   1   1    3      3    2   10        644683
644687   1   1    3      3    2   10        644687
644693   1   1    3      3    2   10        644693

[311831 rows x 7 columns]

In [140]:
df_combined = df_combined.rename(columns={ "ADI":"ADI_2001", "BF":"BF_2001" , "FC":"FC_2001" , "ASSET":"ASSET_2001" , "LIT":"LIT_2001" , "MSW" : "MSW_2001" })

In [141]:
df_combined

        BF_2001  FC_2001  MSW_2001  ...  LIT_2001  ADI_2001  village_code
27378         1        1         1  ...         2         7         27378
27379         1        1         1  ...         2         7         27379
27380         1        1         1  ...         2         7         27380
27381         1        1         1  ...         2         7         27381
27382         1        1         1  ...         2         7         27382
...         ...      ...       ...  ...       ...       ...           ...
644661        1        1         3  ...         2        10        644661
644682        1        1         3  ...         2         9        644682
644683        1        1         3  ...         2        10        644683
644687        1        1         3  ...         2        10        644687
644693        1        1         3  ...         2        10        644693

[311831 rows x 7 columns]

In [142]:
df_combined = df_combined.merge(df_ground_truth_2011,how='inner',left_on='village_code',right_on='village_code')

In [143]:
df_combined

        BF_2001  FC_2001  MSW_2001  ASSET_2001  ...  FC  ASSET  LIT  MSW
0             1        1         1           2  ...   1      3    3    3
1             1        1         1           2  ...   1      3    3    3
2             1        1         1           2  ...   1      3    3    3
3             1        1         1           2  ...   1      3    3    3
4             1        1         1           2  ...   1      3    3    3
...         ...      ...       ...         ...  ...  ..    ...  ...  ...
311826        1        1         3           3  ...   3      3    3    3
311827        1        1         3           2  ...   3      3    3    3
311828        1        1         3           3  ...   3      3    3    3
311829        1        1         3           3  ...   3      3    3    3
311830        1        1         3           3  ...   3      3    3    3

[311831 rows x 13 columns]

In [144]:
df_combined = df_combined.rename(columns={ "ADI":"ADI_2011", "BF":"BF_2011" , "FC":"FC_2011" , "ASSET":"ASSET_2011" , "LIT":"LIT_2011" , "MSW" : "MSW_2011" })

In [145]:
df_combined

        BF_2001  FC_2001  MSW_2001  ...  ASSET_2011  LIT_2011  MSW_2011
0             1        1         1  ...           3         3         3
1             1        1         1  ...           3         3         3
2             1        1         1  ...           3         3         3
3             1        1         1  ...           3         3         3
4             1        1         1  ...           3         3         3
...         ...      ...       ...  ...         ...       ...       ...
311826        1        1         3  ...           3         3         3
311827        1        1         3  ...           3         3         3
311828        1        1         3  ...           3         3         3
311829        1        1         3  ...           3         3         3
311830        1        1         3  ...           3         3         3

[311831 rows x 13 columns]

In [146]:
df_combined = df_combined.merge(df_2019,how='inner',left_on='village_code',right_on='village_code')

In [147]:
df_combined

        BF_2001  FC_2001  MSW_2001  ASSET_2001  ...  MSW  ASSET  LIT  ADI
0             1        1         1           2  ...    3      3    3   13
1             1        1         1           2  ...    3      3    3   13
2             1        1         1           2  ...    3      3    3   13
3             1        1         1           2  ...    3      3    3   11
4             1        1         1           2  ...    3      3    3   13
...         ...      ...       ...         ...  ...  ...    ...  ...  ...
305454        1        1         3           3  ...    3      3    2   14
305455        1        1         3           2  ...    3      3    2   12
305456        1        1         3           3  ...    3      3    2   14
305457        1        1         3           3  ...    3      3    2   12
305458        1        1         3           3  ...    3      3    2   10

[305459 rows x 19 columns]

In [148]:
df_combined = df_combined.rename(columns={ "ADI":"ADI_2019", "BF":"BF_2019" , "FC":"FC_2019" , "ASSET":"ASSET_2019" , "LIT":"LIT_2019" , "MSW" : "MSW_2019" })

In [149]:
df_combined

        BF_2001  FC_2001  MSW_2001  ...  ASSET_2019  LIT_2019  ADI_2019
0             1        1         1  ...           3         3        13
1             1        1         1  ...           3         3        13
2             1        1         1  ...           3         3        13
3             1        1         1  ...           3         3        11
4             1        1         1  ...           3         3        13
...         ...      ...       ...  ...         ...       ...       ...
305454        1        1         3  ...           3         2        14
305455        1        1         3  ...           3         2        12
305456        1        1         3  ...           3         2        14
305457        1        1         3  ...           3         2        12
305458        1        1         3  ...           3         2        10

[305459 rows x 19 columns]

# Get other data from previous dataframe

In [65]:
df_ground_truth_bf = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/5.ADI_Analysis/2011_Original(Ground_Truth)_ADI_without_outlier/2011_ADI_orginal_bf_without_outlier.pickle','rb'))

In [66]:
df_ground_truth_bf

       State District Subdistt Town/Village(Code)  ... BF_RUD BF_INT BF_ADV BF_ADI
0          3       35      200              27378  ...   69.4    0.0   30.6      1
1          3       35      200              27379  ...   95.9    0.0    4.2      1
2          3       35      200              27380  ...   70.8    0.0   29.0      1
3          3       35      200              27381  ...   81.6   13.3    4.9      1
4          3       35      200              27382  ...   87.4    0.0   12.4      1
...      ...      ...      ...                ...  ...    ...    ...    ...    ...
340948    33      633     5902             644661  ...   79.3   11.8    8.9      1
340949    33      633     5902             644682  ...   35.9    6.7   52.4      3
340950    33      633     5902             644683  ...   57.2   17.1   25.4      3
340951    33      633     5902             644687  ...   73.2    8.1   18.7      1
340952    33      633     5902             644693  ...   41.3   24.3   34.5      3

[340953 rows x 10 columns]

In [67]:
dist_centre = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/5.ADI_Analysis/2011_2001_village_ids_ditrict_centre_dist_with_inverse_also_and_std_scalar.pickle','rb'))

In [68]:
dist_centre

                village_id_2001  ... inverted_dist
village_id_2011                  ...
628551.0                  400.0  ...      0.361418
628556.0                  900.0  ...     -0.006575
628553.0                  600.0  ...      0.192981
628554.0                  700.0  ...      0.052412
628632.0                 8400.0  ...     -0.269584
...                         ...  ...           ...
209407.0             10247500.0  ...     -0.165560
209403.0             10247100.0  ...     -0.168184
209411.0             10247900.0  ...     -0.147151
209412.0             10248000.0  ...     -0.109121
209417.0             10248500.0  ...     -0.073833

[340683 rows x 4 columns]

In [150]:
previous_combined_1 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/5.ADI_Analysis/final_data/combined_data_final_different_population_with_all_year_literacy_msl_sc_st_pop.pickle','rb'))

In [151]:
previous_combined_1

           BF_2011  FC_2011  MSW_2011  ...  MSL_2001  LIT_2019  MSL_2019
2011_code                              ...
27378            1        1         3  ...         2         3         3
27379            1        1         3  ...         2         3         3
27380            1        1         3  ...         2         2         3
27381            1        1         3  ...         2         3         3
27382            1        1         3  ...         2         3         3
...            ...      ...       ...  ...       ...       ...       ...
644661           1        3         3  ...         3         3         3
644682           3        3         3  ...         3         3         3
644683           3        3         3  ...         3         3         3
644687           1        3         3  ...         3         2         3
644693           3        3         3  ...         3         2         3

[308011 rows x 51 columns]

In [71]:
previous_combined_2 = pickle.load(open('/content/drive/MyDrive/Scripts_and_Data_Transfer/5.ADI_Analysis/final_data/combined_data_final_different_population_with_literacy_msl_categorized_kmeans_sc_st_pop.pickle','rb'))

In [72]:
previous_combined_2

           BF_2011  FC_2011  MSW_2011  ...  P_SC_2011  P_SC_2001  P_ST_2001
2011_code                              ...
27378            1        1         3  ...        321        261          0
27379            1        1         3  ...        127        100          0
27380            1        1         3  ...       1129        905          0
27381            1        1         3  ...        239        749          0
27382            1        1         3  ...        637         67          0
...            ...      ...       ...  ...        ...        ...        ...
644661           1        3         3  ...        288        178          0
644682           3        3         3  ...       1526        474          0
644683           3        3         3  ...       1368       1065          0
644687           1        3         3  ...       1903       1618          0
644693           3        3         3  ...       2130       1925          0

[308011 rows x 47 columns]

In [152]:
filter_req_data = previous_combined_1[['2001_cc_code',"VILL_CODE_2001",	"DIST_CODE_2001","STATE_CODE_2001" ,"VILL_CODE_2011",	"DIST_CODE_2011" , "STATE_CODE_2011" , "distance_district_centre" ,	"dc_score_none_none_old" ,	"inverted_dist" ,	"inverted_dist_and_std_scalar" ,	"total_population_2001" ,	"total_population_2011","rate_of_population_growth_2001_to_2011"	,"total_population_2019","P_LIT_2011","M_LIT_2011","F_LIT_2011","P_ILL_2011","M_ILL_2011","F_ILL_2011","literacy_percent_2011","P_ST_2011","P_SC_2011",	"P_SC_2001",	"P_ST_2001"]]

In [153]:
filter_req_data

               2001_cc_code VILL_CODE_2001  ... P_SC_2001 P_ST_2001
2011_code                                   ...
27378       301000100000500       00000500  ...       261         0
27379       301000100000600       00000600  ...       100         0
27380       301000100000700       00000700  ...       905         0
27381       301000100000800       00000800  ...       749         0
27382       301000100000900       00000900  ...        67         0
...                     ...            ...  ...       ...       ...
644661     3310000700779700       00779700  ...       178         0
644682     3310000700781800       00781800  ...       474         0
644683     3310000700781900       00781900  ...      1065         0
644687     3310000700782300       00782300  ...      1618         0
644693     3310000700782900       00782900  ...      1925         0

[308011 rows x 26 columns]

# Combine other data from previous data frame and time series data

In [154]:
df_combined_final = filter_req_data.merge(df_combined,how='inner',left_on=filter_req_data.index ,right_on='village_code')

In [155]:
df_combined_final

            2001_cc_code VILL_CODE_2001  ... LIT_2019 ADI_2019
0        301000100000500       00000500  ...        3       13
1        301000100000600       00000600  ...        3       13
2        301000100000700       00000700  ...        3       13
3        301000100000800       00000800  ...        3       11
4        301000100000900       00000900  ...        3       13
...                  ...            ...  ...      ...      ...
305452  3310000700779700       00779700  ...        2       14
305453  3310000700781800       00781800  ...        2       12
305454  3310000700781900       00781900  ...        2       14
305455  3310000700782300       00782300  ...        2       12
305456  3310000700782900       00782900  ...        2       10

[305457 rows x 45 columns]

In [156]:
del df_combined_final['village_code']

In [157]:
df_combined_final

            2001_cc_code VILL_CODE_2001  ... LIT_2019 ADI_2019
0        301000100000500       00000500  ...        3       13
1        301000100000600       00000600  ...        3       13
2        301000100000700       00000700  ...        3       13
3        301000100000800       00000800  ...        3       11
4        301000100000900       00000900  ...        3       13
...                  ...            ...  ...      ...      ...
305452  3310000700779700       00779700  ...        2       14
305453  3310000700781800       00781800  ...        2       12
305454  3310000700781900       00781900  ...        2       14
305455  3310000700782300       00782300  ...        2       12
305456  3310000700782900       00782900  ...        2       10

[305457 rows x 44 columns]

In [158]:
df_combined_final['index_col_village_code_2011'] = df_combined_final['VILL_CODE_2011']

In [159]:
df_combined_final = df_combined_final.set_index(df_combined_final['index_col_village_code_2011'])

In [160]:
del df_combined_final['index_col_village_code_2011']

In [161]:
df_combined_final

                                 2001_cc_code  ... ADI_2019
index_col_village_code_2011                    ...
27378                         301000100000500  ...       13
27379                         301000100000600  ...       13
27380                         301000100000700  ...       13
27381                         301000100000800  ...       11
27382                         301000100000900  ...       13
...                                       ...  ...      ...
644661                       3310000700779700  ...       14
644682                       3310000700781800  ...       12
644683                       3310000700781900  ...       14
644687                       3310000700782300  ...       12
644693                       3310000700782900  ...       10

[305457 rows x 44 columns]

In [109]:
#pickle.dump(df_combined_final,open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/final_combined_temporal_corrected_ADI_for_2001_2019_ground_truth_ADI_2011_variables_predicted_from_arch2_pop_sc_st_lit_village_data.pkl','wb'))

In [162]:
pickle.dump(df_combined_final,open('/content/drive/MyDrive/Scripts_and_Data_Transfer/3.Arch_2_Procedure/5.Train_Regression_and_Classification_Models/Outputs/Time_Series_Output/final_combined_without_temporal_correction_arch2_predicted_ADI_for_2001_2019_ground_truth_ADI_2011_variables_predicted_from_arch2_pop_sc_st_lit_village_data.pkl','wb'))